### ISSUE TITLE
is this project still active

### ISSUE THREAD

**Issue by QWIILXEY** [BluCFE/GChamber_Release#1]
i'm just curious

**Comment by BluCFE** [comment]
Hey! I'm still alive but have been crazy busy IRL. I really want to get back to working on it and properly open source the code some time soon so maybe some people can then collaborate with me to make up for my lack of time. 
Lots of cool features still planned, so keep your eyes out for updates!

**Comment by QWIILXEY** [comment]
that's nice to hear, i'm glad that this project is still active because compared to all the other vr gooning apps i've used this one has to be my favorite out of them all (especially since GChamber has support for images and gifs)

Also i hope you get around to fully open sourcing the code since i wanna contribute to it
